language: java
sudo: false # faster builds

jdk:
    - oraclejdk11
    - openjdk10
    - oraclejdk9
    - oraclejdk8
    - openjdk7

script:
    - mvn clean package

after_success:
    - bash <(curl -s https://codecov.io/bash)